version: "3"

services:
  ddns:
    container_name: ddns
    image: ddns
    environment:
      TOKEN: 'Token Here'
      DOMAIN: 'example.com'
      CNAME: 'cname'
      TZ: 'Asia/Kolkata'
    restart: unless-stopped
